version: "3"
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.controller
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yml
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yml
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  agent1:
    build: 
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - JENKINS_AGENT_NAME=agent1
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_WEB_SOCKET=true
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    depends_on:
      - jenkins

  agent2:
    build: 
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - JENKINS_AGENT_NAME=agent2
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_WEB_SOCKET=true
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    depends_on:
      - jenkins
